export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_VIEW_REQUEST = "ORDER_VIEW_REQUEST";
export const ORDER_VIEW_SUCCESS = "ORDER_VIEW_SUCCESS";
export const ORDER_VIEW_FAIL = "ORDER_VIEW_FAIL";
export const ORDER_VIEW_RESET = "ORDER_VIEW_RESET";

export const ORDER_ADMIN_VIEW_REQUEST = "ORDER_ADMIN_VIEW_REQUEST";
export const ORDER_ADMIN_VIEW_SUCCESS = "ORDER_ADMIN_VIEW_SUCCESS";
export const ORDER_ADMIN_VIEW_FAIL = "ORDER_ADMIN_VIEW_FAIL";
export const ORDER_ADMIN_VIEW_RESET = "ORDER_ADMIN_VIEW_RESET";

export const ORDER_ADMIN_DELIVER_REQUEST = "ORDER_ADMIN_DELIVER_REQUEST";
export const ORDER_ADMIN_DELIVER_SUCCESS = "ORDER_ADMIN_DELIVER_SUCCESS";
export const ORDER_ADMIN_DELIVER_FAIL = "ORDER_ADMIN_DELIVER_FAIL";
export const ORDER_ADMIN_DELIVER_RESET = "ORDER_ADMIN_DELIVER_RESET";
